version = 1

test_patterns = ["__tests__/**"]

exclude_patterns = [
    ".chglog/**",
    ".github/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "standard"
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
